### ISSUE TITLE
Make mailto SPA work with docker env

### ISSUE THREAD

**Issue by alagane** [linagora/esn-frontend-mailto#84]
On dev mode (running devserver with docker proxy for mailto)
I have some errors
![image.png](https://images.zenhubusercontent.com/5730988ebf93871ccd9ab837/6a807c13-e0be-40d3-b693-e2dabe093d8f)
XHR GET http://backend.open-paas.org.local/api/user?_=1624269420084 [HTTP/1.1 401 Unauthorized 65ms]
Uncaught (in promise) Unauthorized
[WDS] Disconnected! client:172
XHR POST http://backend.open-paas.org.local/api/jwt/generate [HTTP/1.1 401 Unauthorized 67ms]

Then (probably not related)
GET http://backend.open-paas.org.local/api/themes/60d0477d02a62500a98ec505/logo [HTTP/1.1 401 Unauthorized 98ms]
The application with name Account does not have an icon available. A fallback icon will be used instead. esn-app-grid.entry.js:24
GET http://mailto.open-paas.org.local/mailto/images/white-logo.svg [HTTP/1.1 404 Not Found 6ms]
Img fallback src images/white-logo.svg not found. core.js:133

Main requests failing are
http://backend.open-paas.org.local/api/user?_=1624269420084 => Unauthorized (though other requests to the same API works after this one)
http://backend.open-paas.org.local/api/jwt/generate => Unauthorized
This request it madeo nly one time, compared to inbox SPA where subsequent requests to this url works (but the first fails too).

**Comment by tanandy** [comment]
cc @rezk2ll

**Comment by alagane** [comment]
Sooo, it seems the loading of the application is blocked by the fetch user request
bootstrapSession definition:
https://github.com/linagora/esn-frontend-common-libs/blob/main/src/frontend/js/modules/session.js#L139
called here:
https://github.com/linagora/esn-frontend-mailto/blob/main/src/app/app.run.js#L12

**Comment by tanandy** [comment]
cc @renaudboyer @asmaNode

**Comment by alagane** [comment]
May be related to this commit: https://github.com/linagora/esn-frontend-mailto/commit/2c381d074e17815eb85a2d80442a4f9814c0ccac#diff-7813a7413b4f7d58b802db3df4ee414a7c2b5ee3d0d7aeb19872015dc77287d7

**Comment by renaudboyer** [comment]
Fixed by https://github.com/linagora/esn-frontend-common-libs/pull/229
